version: "3"

services:
  app-backend: ## Deliver IT
    build:
      context: .
      dockerfile: dockerfile
    image: deliverit/app-backend
    container_name: app-backend
    restart: unless-stopped
    ports:
      - "3333:3333"
    volumes:
      - app-volume-backend:/usr/app:rw
    networks:
      - app-network-backend
    command: yarn dev
volumes:
  app-volume-backend:
networks:
  app-network-backend:
